#!/bin/bash

echo "COPYing all the files from llvm/build to BFC_StaticAnalysis and llvm/lib folders"
#cp -r /export/home/hzhang86/BForChapel/BFC_StaticAnalysis/* /export/home/hzhang86/chapel/chapel/third-party/llvm/build/linux64-gnu/lib/Transforms/BFC
cp -r /export/home/hzhang86/chapel/chapel/third-party/llvm/build/linux64-gnu/lib/Transforms/BFC/* /export/home/hzhang86/BForChapel/BFC_StaticAnalysis/ 
cp -r /export/home/hzhang86/chapel/chapel/third-party/llvm/build/linux64-gnu/lib/Transforms/BFC/* /export/home/hzhang86/chapel/chapel/third-party/llvm/llvm/lib/Transforms/BFC/


