##===- lib/Transforms/Hello/Makefile -----------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../../..
LIBRARYNAME = BFC
LOADABLE_MODULE = 1
USEDLIBS =
#Added by Hui to enable -std=c++11 in the compilation
#ENABLE_CXX11 := 1

include $(LEVEL)/Makefile.common

